### ISSUE TITLE
method to show_query to show what SQL PRQL will generate?

### ISSUE THREAD

**Issue by cboettig** [snth/pq#31]
Is there a method similar to [`dplyr::show_query()`](https://dplyr.tidyverse.org/reference/explain.html) which will show the corresponding SQL that is generated by a PRQL command chain?  I find this can be very helpful, especially when seeking to become more familiar with the PRQL / piped syntax!

**Comment by eitsupi** [comment]
@cboettig Have you tried `prqlc`? It is a CLI tool that provides simple query compilation.

We need to build it on our side as there are no binaries in the GitHub release......

```sh
$ cargo install prqlc
$ echo 'from hello | select world' | prqlc compile
SELECT
  world
FROM
  hello

-- Generated by PRQL compiler version:0.6.1 (https://prql-lang.org)
```
